services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
           # - './ssl:/certs'
            - './data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
        #command:
           # --ssl
            #--sslcert /certs/server.crt
            #--sslkey /certs/server.key

